// react/src/App.jsx
import { useState } from 'react'

function App() {

  const [show, setShow] = useState(true),
        [list, setList] = useState([1, 2, 3])

  const listItems =
  <ul>
    {list.map((item) => <li>{item}</li>)}
  </ul>

  function Render() {
    if (show && list.length)
      return listItems
    else
      if ( list.length )
        return <p>List is not empty, but hidden.</p>
      else
        return <p>List is empty.</p>
  }

  return (
    <div className="App">
      <button onClick={() => setShow(!show)}>Toggle List</button>
      <button onClick={() => (list.push(list.length + 1), setList([...list]))}>Push Number</button>
      <button onClick={() => (list.pop(), setList([...list]))}>Pop Number</button>
      <button onClick={() => setList([...list.reverse()])}>Reverse List</button>

      {Render()}
    </div>
  )
}

export default App

// vue/src/App.vue
<script>
  export default {
    data() {
      return {
        show: true,
        list: [1, 2, 3]
      }
    }
  }
</script>

<template>
  <button @click="show = !show">Toggle List</button>
  <button @click="list.push(list.length + 1)">Push Number</button>
  <button @click="list.pop()">Pop Number</button>
  <button @click="list.reverse()">Reverse List</button>

  <ul v-if="show && list.length">
    <li v-for="item of list">{{ item }}</li>
  </ul>
  <p v-else-if="list.length">List is not empty, but hidden.</p>
  <p v-else>List is empty.</p>
</template>
